.catalog:
  name: Storm Cluster
  version: Storm-0.9.3-rancher1
  description: |
    Apache Storm cluster.
  minimum_rancher_version: v0.56.0
  maintainer: "Pawan Kumar <monu.pawan@gmail.com>"
  uuid: zk-0
  questions:
    - variable: "nimbus_scale"
      description: "Number of Nimbus nodes"
      label: "nimbus Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "supervisor_scale"
      description: "Number of supervisor nodes"
      label: "supervisor Nodes:"
      required: true
      default: 3
      type: "int"
    - variable: "ui_scale"
      description: "Number of ui nodes"
      label: "ui Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "zk_link"
      description: |
        Choose the Zookeeper service to use. 
        It's really recommended a dedicated zookeeper service just for Nifi.
      label: "Zookeeper stack/service"
      default: "zookeeper/zk"
      required: true
      type: "service"
    - variable: "HazelcastETL_link"
      description: |
        Choose the Hazelcast service to use. 
      label: "HazelcastETL stack/service"
      default: "HazelcastETL/Loader"
      required: true
      type: "service"
    - variable: "HazelcastNONETL_link"
      description: |
        Choose the Hazelcast service to use. 
      label: "HazelcastNONETL stack/service"
      default: "HazelcastNONETL/Loader"
      required: true
      type: "service"
    - variable: "Kafka_link"
      description: |
        Choose the Kafka service to use. 
      label: "Kafka stack/service"
      default: "kafka/broker"
      required: true
      type: "service"
    - variable: "RabbitMq_link"
      description: |
        Choose the RabbitMq service to use. 
      label: "RabbitMq stack/service"
      default: "rabbit1"
      required: true
      type: "service"
nimbus:
 scale: ${nimbus_scale}
supervisor:
 scale: ${supervisor_scale}
ui:
 scale: ${ui_scale}
